// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"KRD_MZ_Dice","status":true,"description":"サイコロを振り、結果を変数に入れます。","parameters":{"swRolling":"1","varDice":"6","plusX":"0","plusY":"0"}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}},
{"name":"AltSaveScreen","status":true,"description":"Alternative save/load screen layout.","parameters":{}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"NPCProfitLabel","status":true,"description":"在事件/NPC頭上顯示指定變數的數值，可用於顯示獲利金額 v1.0","parameters":{"showSwitchId":"30","fontSize":"24","offsetY":"-70","showZero":"true"}},
{"name":"ForceStretch","status":true,"description":"強制網頁版遊戲自動延展填滿可用空間（適合 iframe / 平板橫向）","parameters":{}}
];
